/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz_3;

import quiz_3.models.EmptyListException;
import quiz_3.models.InvalidInputException;
import quiz_3.views.Menu;

public class App {

    public static void main(String[] args) {
        Menu menu = new Menu();
        try{
            menu.render();
        } catch (InvalidInputException invalidInpunt){
            System.out.println(invalidInpunt.getMessage());
        } catch (EmptyListException emptyList){
            System.out.println(emptyList.getMessage());
        }
    }
}
